version: "3.9"

services:
  nuxt-dev:
    build: .
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    # depends_on:
    #   - db
  # db:
  #   image: mysql:8.1.0
  #   ports:
  #     - 3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_DATABASE}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   restart: always
  #   volumes:
  #     - /var/lib/mysql
